Security jwt
SerhiiAN/Spring-Boot-intro pull request #10
Opened 2024-07-09 20:08 UTC by SerhiiAN

2024-07-10 11:52 UTC, MentorMateAcademy requested changes

2024-07-10 11:52 UTC, MentorMateAcademy commented on src/main/java/mate/academy/intro/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
save it to constants

2024-07-11 12:15 UTC, Elena-Bruyako requested changes
some comments

2024-07-11 12:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);

```

2024-07-11 12:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/security/JwtAuthenticationFilter.java
> +    private static final String TOKEN_STARTS = "Bearer ";
```suggestion
    private static final String TOKEN_HEADER = "Bearer ";

```

2024-07-12 13:13 UTC, okuzan requested changes
Almost there!

2024-07-12 13:13 UTC, okuzan commented on src/main/java/mate/academy/intro/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(TOKEN_HEADER)) {
            return bearerToken.substring(TOKEN_HEADER.length());
```
that's where we get 7 from, code should reflect this

2024-07-13 08:55 UTC, Elena-Bruyako requested changes
Well done. See comment

2024-07-13 08:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```
For String

2024-07-13 08:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
same

2024-07-13 17:31 UTC, sarakhmen approved these changes
lgtm!

2024-07-14 03:05 UTC, merged