Spring boot practice category
SerhiiAN/Spring-Boot-intro pull request #11
Opened 2024-07-15 02:22 UTC by SerhiiAN

2024-07-16 08:40 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/controller/BookController.java
> +    @Transactional
replace to service layer

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/dto/book/CreateBookRequestDto.java
> +    private Set<Long> categoryIds;
add validation

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +            name = "book_category",
```suggestion
            name = "books_categories",

```

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Category.java
> +@Table(name = "category")
```suggestion
@Table(name = "categories")
```

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Category.java
> +    private Set<Book> books = new HashSet<>();
```suggestion
```

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Category.java
> +    @ManyToMany(mappedBy = "categories", fetch = FetchType.LAZY)
```suggestion
```

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/category/CategoryServiceImpl.java
> +                .map(categoryMapper::toDto).toList();
```suggestion
                .map(categoryMapper::toDto)
                .toList();
```

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/08-create-category-table-and-change-book-table.yaml
> +            tableName: category
```suggestion
            tableName: categories
```

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/08-create-category-table-and-change-book-table.yaml
> +            tableName: book_category
```suggestion
            tableName: books_categories
```

2024-07-16 08:40 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/08-create-category-table-and-change-book-table.yaml
> +databaseChangeLog:
rename file, you don't change book table
it's better create separate changelogs for create category and create book-category

2024-07-17 14:02 UTC, Elena-Bruyako requested changes
see comments

2024-07-17 14:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +    @Transactional
```suggestion
```

2024-07-17 14:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +    @Transactional
```suggestion
```

2024-07-17 14:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +    @Transactional
```suggestion
```

2024-07-17 14:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +    @Transactional
```suggestion
```

2024-07-17 14:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +    @Transactional
Add `@Transactional `for save method, also add there
`book.setCategories.....`

Add `@Transactional` for update method

2024-07-19 08:58 UTC, Elena-Bruyako requested changes
see pr

2024-07-19 08:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/dto/book/CreateBookRequestDto.java
> +    @NotNull(message = "At least one category ID is required.")
```suggestion
    @NotEmpty(message = "At least one category ID is required.")
```

2024-07-19 08:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/controller/BookController.java
> +    public List<BookDto> search(@ModelAttribute BookSearchParameters searchParameters,
Why do you need `@ModelAttribute`?

2024-07-19 08:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

Lazy by default

2024-07-19 08:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +    @Transactional
remove

2024-07-19 08:58 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
>      }
Why method search is absent in BookService interface?

2024-07-20 16:55 UTC, MentorMateAcademy requested changes

2024-07-20 16:55 UTC, MentorMateAcademy commented on src/main/java/mate/academy/intro/repository/category/CategoryRepository.java
> +@Repository
```suggestion

```

2024-07-22 09:07 UTC, MentorMateAcademy requested changes

2024-07-22 09:07 UTC, MentorMateAcademy commented on src/main/java/mate/academy/intro/repository/book/BookRepository.java
>  @Repository
```suggestion

```

2024-07-22 09:07 UTC, MentorMateAcademy commented on src/main/java/mate/academy/intro/repository/book/BookRepository.java
>  @Repository
you can clear this anno

2024-07-23 09:40 UTC, Elena-Bruyako requested changes
see comments

2024-07-23 09:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/controller/CategoryController.java
> +@RequestMapping("/api/categories")
```suggestion
@RequestMapping("/categories")

```

2024-07-23 09:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +            name = "book_categories",
```suggestion
            name = "books_categories",
```

2024-07-23 09:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Category.java
> +@Where(clause = "is_deleted=FALSE")
`@Where` is deprecated

2024-07-23 09:40 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/user/UserServiceImpl.java
> +        UserResponseDto responseDto = userMapper.toUserResponseDto(userRepository.save(user));
why do you need to make this changes?

2024-07-24 17:51 UTC, okuzan approved these changes

2024-07-24 19:07 UTC, merged