Spring boot practice shopping cart
SerhiiAN/Spring-Boot-intro pull request #12
Opened 2024-07-18 21:45 UTC by SerhiiAN

2024-07-20 11:46 UTC, okuzan requested changes
please fix validation

2024-07-20 11:46 UTC, okuzan commented on src/main/java/mate/academy/intro/dto/shoppingcart/CreateCartItemRequestDto.java
> +        @NotNull(message = "Book ID is mandatory.")
for Long ids we can use @Positive

2024-07-20 11:46 UTC, okuzan commented on src/main/java/mate/academy/intro/dto/shoppingcart/UpdateCartItemRequestDto.java
> +        @NotNull(message = "Quantity is mandatory.")
primitive cannot be null

2024-07-21 15:53 UTC, MentorMateAcademy approved these changes

2024-07-21 15:53 UTC, MentorMateAcademy commented on src/main/java/mate/academy/intro/repository/shopping/cart/ShoppingCartRepository.java
> +@Repository
Repository anno is redundant in JPA

2024-07-24 19:32 UTC, merged