Spring boot practice docker
SerhiiAN/Spring-Boot-intro pull request #14
Opened 2024-07-26 20:27 UTC by SerhiiAN

2024-07-27 12:50 UTC, okuzan requested changes

2024-07-27 12:50 UTC, okuzan commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
5005 - debug port, use env var

2024-07-27 12:50 UTC, okuzan commented on Dockerfile
> +EXPOSE ${SPRING_DOCKER_PORT}
add new empty line

2024-07-27 12:50 UTC, okuzan commented on .env
> +DEBUG_PORT=5005
add .env.template to the project with actual values removed, add .env to gitignore, use git rm --cached .env to keep local copy but remove from remote origin

2024-07-28 16:21 UTC, MentorMateAcademy approved these changes

2024-07-28 16:51 UTC, merged