Branch dto
SerhiiAN/Spring-Boot-intro pull request #3
Opened 2024-06-17 06:03 UTC by SerhiiAN

2024-06-17 07:14 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments.

2024-06-17 07:14 UTC, Elena-Bruyako commented on pom.xml
> -
Remove blank lines in properties block

2024-06-17 07:14 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")

```

2024-06-17 07:14 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
>  @Data
Don't use `@Data` for entities, it could cause a lot of issues

2024-06-17 07:14 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
>  @Data
Add constraint for private BigDecimal price;
Also, private String author; shouldn't be unique

2024-06-17 07:14 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +            throw e;
Am I right, that you don't return a book, but throw e? 
If so, please fix the logic

2024-06-17 07:14 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +            if (transaction != null && transaction.isActive()) {
if you are using try with resources, rollback won't happened, because session will close before catch block
use try-catch-finally

2024-06-17 07:14 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
revert please

2024-06-17 16:24 UTC, SerhiiAN commented on src/main/java/mate/academy/intro/controller/BookController.java
> +@RequestMapping(value = "/books")
Виправив

2024-06-17 16:24 UTC, SerhiiAN commented on src/main/java/mate/academy/intro/model/Book.java
>  @Data
виправив

2024-06-17 16:27 UTC, SerhiiAN commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +            throw e;
Це код з гілки мастер, а це стара версія. Я робив код в гілці branch_dto, там трохи по іншому. Так, як Вам треба.

2024-06-17 16:27 UTC, SerhiiAN commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +            if (transaction != null && transaction.isActive()) {
цього теж немає в гілці branch_dto

2024-06-17 16:28 UTC, SerhiiAN commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
Це в гілці branch_dto так і є.

2024-06-17 16:35 UTC, SerhiiAN commented
Перевіряйте гілку branch_dto

2024-06-17 19:32 UTC, sarakhmen commented
це і є гілка [branch_dto](https://github.com/SerhiiAN/Spring-Boot-intro/tree/branch_dto) 
<img width="652" alt="image" src="https://github.com/SerhiiAN/Spring-Boot-intro/assets/53354844/ec249894-390b-4d48-8274-6110ef5e28c2">
Перевір, чи ти запушив всі зміни в гітхаб

2024-06-17 21:09 UTC, SerhiiAN commented
![Знімок екрана 2024-06-17 145802](https://github.com/SerhiiAN/Spring-Boot-intro/assets/107151150/22908bf1-9d94-444e-be1f-d665e067008e)
![Знімок екрана 2024-06-17 145726](https://github.com/SerhiiAN/Spring-Boot-intro/assets/107151150/2b671266-fcd2-470d-a212-e1b415a9cb31)

Можливо я щось не розумію, можливо погано розумію англійську, але я не розумію що від мене тут вимагається. Може поясніть українською. 
на фрагменті кода що на скріні червоні строки коду треба видалити, а зелені додати, але на іншому скріні я відкрив цей код з гіт хабу, й там не бачу такого коду, там під номерами цих строках інший код. Але в гілці мастер цього репозиторію дійсно такі строки є, чи мені треба обидві гілки змінити?

2024-06-18 19:43 UTC, sarakhmen commented
стосовно твого останньо коментаря - зверни увагу на стрічку 27, проблема досі не усунута, хоча Олена її згадувала. Щось ти пофіксив, а щось - ні. Пройдись по всіх коментах і виправ, де потрібно :)

2024-06-18 19:44 UTC, sarakhmen requested changes
Let's change your solution as per last comment

2024-06-19 06:26 UTC, Elena-Bruyako requested changes
Let's fix some comments

2024-06-19 06:26 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +@ToString
Remove these annotations
```
@ToString
@EqualsAndHashCode
@NoArgsConstructor
```

2024-06-19 06:26 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
```suggestion
spring.jpa.hibernate.ddl-auto=create-drop
```

2024-06-19 06:26 UTC, Elena-Bruyako commented on pom.xml
>              <artifactId>commons-dbcp2</artifactId>
Why do you need this dependency?

2024-06-19 06:58 UTC, Elena-Bruyako approved these changes
Good job!

2024-06-19 19:03 UTC, merged