executed the task
SerhiiAN/Spring-Boot-intro pull request #4
Opened 2024-06-20 22:45 UTC by SerhiiAN

2024-06-21 06:02 UTC, Elena-Bruyako requested changes
Good job, let's fix some comments

2024-06-21 06:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +    @Column(name = "cover_image")
```suggestion
```

2024-06-21 06:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/controller/BookController.java
> +    public void updateById(@PathVariable Long id) {
Pass the request DTO, 
<img width="748" alt="Screenshot 2024-06-21 at 08 59 33" src="https://github.com/SerhiiAN/Spring-Boot-intro/assets/14053156/87054421-031b-4eaf-a73a-cb88d1270035">

2024-06-21 06:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +        book.setDeleted(true);
```suggestion
       bookMapper.updateBookFromDto(bookDto, book);

```

2024-06-23 05:48 UTC, Elena-Bruyako requested changes
Need to fix some comments

2024-06-23 05:48 UTC, Elena-Bruyako commented on pom.xml
> +            <version>4.27.0</version>
```suggestion
            <version>${liquibase.version}</version>
```

spring-boot-parent provides this version

2024-06-23 05:48 UTC, Elena-Bruyako commented on pom.xml
> +                <version>4.27.0</version>
```suggestion
                <version>${liquibase.version}</version>
```

2024-06-23 05:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +    @Column(name = "is_deleted", nullable = false, columnDefinition = "TINYINT(1) DEFAULT 0")
```suggestion
    @Column(nullable = false, columnDefinition = "TINYINT(1) DEFAULT 0")
```

Hibernate automatically create column in snake_case style

2024-06-23 05:48 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +
```suggestion
```

2024-06-23 05:48 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-change-column-cover_image-in-table-books.yaml
> +      id: rename-column-cover_image-to-coverImage
remove this changelog

2024-06-23 11:15 UTC, okuzan approved these changes

2024-06-23 11:15 UTC, okuzan commented on src/main/java/mate/academy/intro/model/Book.java
> +@SQLRestriction(value = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(value = "is_deleted = FALSE")
```

2024-06-23 11:15 UTC, okuzan commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +                );
```suggestion
                () -> new EntityNotFoundException("Can not find book " + id));
```

2024-06-23 19:53 UTC, merged